//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Losttbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Losttbl()
        {
            this.AllProductsTbls = new HashSet<AllProductsTbl>();
            this.TopLosttbls = new HashSet<TopLosttbl>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string Category { get; set; }
        public string Location { get; set; }
        public string Details { get; set; }
        public string SubLocation { get; set; }
        public Nullable<System.DateTime> DateOfLost { get; set; }
        public string SubCategory { get; set; }
        public string Type { get; set; }
        public string OwnerName { get; set; }
        public Nullable<int> CellNo { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> SubLocationId { get; set; }
        public string OwnerAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllProductsTbl> AllProductsTbls { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual SubCategory SubCategory1 { get; set; }
        public virtual SubLocation SubLocation1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TopLosttbl> TopLosttbls { get; set; }
    }
}
