//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOF
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Topfoundtbl
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }

        public string Image { get; set; }
        public string Category { get; set; }
        public string Location { get; set; }
        public string Details { get; set; }
        public string SubLocation { get; set; }
        public Nullable<System.DateTime> DateOfFound { get; set; }
        public Nullable<int> FoundId { get; set; }
        public string SubCategory { get; set; }
        public string Type { get; set; }
        public string OwnerName { get; set; }
        public Nullable<int> CellNo { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> SubLocationId { get; set; }
        public string OwnerAddress { get; set; }
        public Nullable<int> UniqueKey { get; set; }
    
        public virtual Category Category1 { get; set; }
        public virtual Foundtbl Foundtbl { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual SubCategory SubCategory1 { get; set; }
        public virtual SubLocation SubLocation1 { get; set; }
    }
}
